### ISSUE TITLE
javascript

### ISSUE THREAD

**Issue by maybesmurf** [surrealdb/surrealdb.js#1]
no types. if only it was written in typescript in the first place

**Comment by tobiemh** [comment]
Hi @maybesmurf, it's not a large library, so adding typescript / converting to typescript won't be too big a task.

In addition our WebAssembly library (coming soon) will have typescript bindings.

If you are experienced in this area do let me know!

**Comment by michaelprichardson** [comment]
Looks like an awesome library! Can help converting to TS if needed?

**Comment by tobiemh** [comment]
@michaelprichardson that would be amazing! Out of interest, should it be in a separate repository (`surrealdb.ts`) or just in this one?

**Comment by michaelprichardson** [comment]
@tobiemh I think this repo will do just fine

**Comment by tobiemh** [comment]
Ok @michaelprichardson, awesome. The only things I would note are:

1. The library needs to work in the browser and on the backend (node.js).

2. The only tricky thing I envisage is that the library uses `WebSocket` in the browser, but uses the `ws` package on the server. Not sure how this can be done in TypeScript.

- This is visible in the [`src/websocket`](https://github.com/surrealdb/surrealdb.js/tree/main/src/websocket) folder.
- And in the [`webpack.config.js`](https://github.com/surrealdb/surrealdb.js/tree/main/webpack.config.js) file:

https://github.com/surrealdb/surrealdb.js/blob/1a633f4c33e42a5cb22b736b60475fd34bbea7ba/webpack.config.js#L17-L20

https://github.com/surrealdb/surrealdb.js/blob/1a633f4c33e42a5cb22b736b60475fd34bbea7ba/webpack.config.js#L52-L55

**Comment by michaelprichardson** [comment]
@tobiemh I noticed that while I was looking through the code. I was going to use a similar method to this, [isomorphic-ws](https://www.npmjs.com/package/isomorphic-ws).

**Comment by tobiemh** [comment]
@michaelprichardson just looking at this a bit closer. We should be able to use the same technique that is already being used. I'll look into this a little more,

**Comment by Choooks22** [comment]
Is anyone currently working on a types / full TypeScript support?
I'd like to take on converting it to a TypeScript package (and maybe some improvements if IE support isn't too important)

**Comment by michaelprichardson** [comment]
@Choooks22 it's been started here https://github.com/surrealdb/surrealdb.js/pull/5 so far but it's just an initial beginning

**Comment by agent-ly** [comment]
> Ok @michaelprichardson, awesome. The only things I would note are:
> 
> 1. The library needs to work in the browser and on the backend (node.js).
> 2. The only tricky thing I envisage is that the library uses `WebSocket` in the browser, but uses the `ws` package on the server. Not sure how this can be done in TypeScript.
> 
> * This is visible in the [`src/websocket`](https://github.com/surrealdb/surrealdb.js/tree/main/src/websocket) folder.
> * And in the [`webpack.config.js`](https://github.com/surrealdb/surrealdb.js/tree/main/webpack.config.js) file:
> 
> https://github.com/surrealdb/surrealdb.js/blob/1a633f4c33e42a5cb22b736b60475fd34bbea7ba/webpack.config.js#L17-L20
> 
> https://github.com/surrealdb/surrealdb.js/blob/1a633f4c33e42a5cb22b736b60475fd34bbea7ba/webpack.config.js#L52-L55

I believe a simpler solution is to either have an adapter class or let the user define what to WebSocket implementation to use themselves with the default being determined if its in the browser or in a node process. In typecript this would be as simple as making a `WebsocketLike` class that defines all the functionality you use in the package

**Comment by Choooks22** [comment]
Simplest would be to just use [isomorphic-ws](https://www.npmjs.com/package/isomorphic-ws), so there's no runtime check needed.

As for injectable ws implementation, I've suggested in the discord to have the ws and http client separated and let the `Surreal` class handle them both, allowing users to trim down the lib if they only need one.

**Comment by JacobZwang** [comment]
Has there been any thought put into strongly typing the query output?
Perhaps some sort of type generation can be used to create something like the below.
```typescript
interface Person {
    name: string;
    age: number;
}

interface Surreal {
    select(thing: `person`): Promise<Person[]>;
    select(thing: `person:${string}`): Promise<Person>;
}
```
