### ISSUE TITLE
Converting QueryResult<RawQueryResult> to Array

### ISSUE THREAD

**Issue by dikovmaxim** [surrealdb/surrealdb.js#102]
Hi. I am trying to execute: SELECT * users WHERE class = $1 AND type = $2 
Using the following code:
export async function ClassTeachers(classname: string){
            const teachers = await Query("SELECT * users WHERE class = $1 AND type = $2", [classname, "teacher"]);
            for (let i = 0; i < teachers.length; i++){
                teachers[i] = teachers[i].username;
            }
        }
Then, I am trying to iterate over the results, but teachers[i].username reports an error: Property 'username' does not exist on type 'QueryResult<RawQueryResult>'. I didnt find any way to convert QueryResult<RawQueryResult> to Array of elements.

**Comment by dikovmaxim** [comment]
I am sorry if I am asking a dumb question, I am pretty new to surrealdb. Unfortunately there is a huge lack of documentation.
P.S. I am Using Typescript node (ts-node)

**Comment by Micnubinub** [comment]
Add the type to where your query is running `db.query<User>` or say `const teachers: User[] = ...`

**Comment by dikovmaxim** [comment]
thx
