### ISSUE TITLE
Minimize the number of http roundtrips (most important when running on the edge)

### ISSUE THREAD

**Issue by happysalada** [surrealdb/surrealdb.js#107]
I couldn't find anything in the documentation for how to minimize the number of http round trips.

When running on the edge (cloudflare workers for example), the number of round trips to the db will affect performance a lot. The ideal scenario is if there is a single roundtrip, you send a jwt and some instructions and then it returns a response or an error.

There are no details for which functions actually do a round trip.
I'm guessing `authenticate` will make a query.
Also potentially any `select, query, ...`, right ?
So everytime I make a query, it's one roundtrip, right ?
So the best would be to try to make all the sql statements fit into a single `query` then there would be 2 round trips, one for the authenticate and one for the query ?

Did I get this right ?

**Comment by Micnubinub** [comment]
Try using [Functions](https://surrealdb.com/docs/surrealql/statements/define/function)

**Comment by happysalada** [comment]
Thanks a lot for the answer!
I'll try functions.
My understanding is that the back and forth can be minimized to 2 round trips, one for authentication and one for a function call. I'll try that in production and will report.

**Comment by kearfy** [comment]
I actually added an experimental HTTP api in the latest release! At that point, if you have the token already you can execute everything in only 1 request!

**Comment by Micnubinub** [comment]
Oh actually it seems I may have misunderstood you question. Functions won't help with reducing the round trips unless you were gonna be running some operations on results of some of your responses

**Comment by happysalada** [comment]
@kearfy it looks like the http experimental client also has an authenticate method. So you would call it with
```
client.authenticate(jwt)
client.query(`...`)
```
but what you are saying is that under the hood this would be only one round trip. Did I understand correctly ?

**Comment by kearfy** [comment]
In the case of the experimental HTTP implementation, the `.authenticate()` function is only used to set the token that will be used to authenticate the HTTP request to the REST api.

**Comment by kearfy** [comment]
Going to close this issue as stale, feel free to leave additional comments!

**Comment by happysalada** [comment]
You answered the question, thanks again !
