### ISSUE TITLE
`db.create` doesn't accept custom interfaces

### ISSUE THREAD

**Issue by AngeloCore** [surrealdb/surrealdb.js#119]
This is my type:
```ts
export interface UserDatabase {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
}
```

And this is my code:
```ts
  const userPayload: UserDatabase = {
    email: body.email,
    password: hashedPassword,
    firstName,
    lastName
  };

  const saved = await db.create(`user:${userID}`, userPayload);
```

And the error is:
`Argument of type 'UserDatabase' is not assignable to parameter of type 'Record<string, unknown>'.
  Index signature for type 'string' is missing in type 'UserDatabase'.`
  
If I add `[key: string]: unknown;` into `UserDatabase`, I don't get the error anymore, but is just a workaround

**Comment by AngeloCore** [comment]
Note: It works with a custom `type` but not with an `interface`

**Comment by kearfy** [comment]
Hi @AngeloCore, thanks for pointing this out. This could theoretically be solved by accepting `{}` or `object` as a type, but this is fundamentally wrong as you accept much more than the objects we intend to accept, as a lot of stuff in JS is an object when you get it's type. This reddit post showcases this really nicely: https://www.reddit.com/r/typescript/comments/tq3m4f/the_difference_between_object_and_recordstring/

With that in mind, `Record<string, unknown>` is the correct type here, but it does mean you cannot use interfaces, at least not the way you do here. 
The `satisfies` keyword was recently introduced in typescript which I'm pretty sure will solve your problem:
https://www.typescriptlang.org/play?#code/C4TwDgpgBAJhC2B7APAFShAHsCA7GAzlAEoQDGiATjMgcJQJa4DmANFAK64DWuiA7rgB8QqAF4oqANwAoGUxyUAZgEMy0BqvVQA3jKgGoYSojAAuKHUYtZAX1kyKuOlH5VuTZuN37Dx0xYA5Dh0gTK2lirADARKDBBEmmoQDk4uAEYm3HgWSdoSeoZGJuZQwQnAYfZyoJBQKt5wSMi1EIhKru6eQrKtUOmNCCit7f1ZeD1AA

Let me know if the following solves your problem!
```typescript
const userPayload = {
    email: body.email,
    password: hashedPassword,
    firstName,
    lastName
} satisfies UserDatabase;
```
