### ISSUE TITLE
`ws` package not installed when using `yarn` package manager

### ISSUE THREAD

**Issue by AngeloCore** [surrealdb/surrealdb.js#121]
```
D:\Programming\Projects\s\s\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:757
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
CustomError: Cannot find package 'ws' imported from D:\Programming\Projects\s\s\node_modules\unws\src\node.mjs
```

From package.json:
```json
"surrealdb.js": "^0.7.2"
```

**Comment by kearfy** [comment]
Hey @AngeloCore could you give some more details on the environment that you are running in? Like node, or browser for example?

**Comment by AngeloCore** [comment]
> Hey @AngeloCore could you give some more details on the environment that you are running in? Like node, or browser for example?

NodeJS v18.14.2

**Comment by kearfy** [comment]
I cannot reproduce this unfortunetly @AngeloCore. Could you get me a reproducable example?

**Comment by AngeloCore** [comment]
> I cannot reproduce this unfortunetly @AngeloCore. Could you get me a reproducable example?

Oops, forgot to say but I'm using esm (module)

**Comment by kearfy** [comment]
Me too :)

**Comment by AngeloCore** [comment]
> Me too :)

I uploaded the files here: https://github.com/AngeloCore/surrealdb-ws-issue

Just run:
- `yarn`
- `node .`

**Comment by kearfy** [comment]
Ha! The one package manager I did not try. The `ws` package is supposed to be installed alongside `unws`. For now, please install the `ws` package manually in your project root, should solve your issue for now...

**Comment by kearfy** [comment]
@AngeloCore this is now live!
