### ISSUE TITLE
Feature: Add backup() and restore() methods

### ISSUE THREAD

**Issue by ntorrey** [surrealdb/surrealdb.js#127]
This is kind of related to https://github.com/surrealdb/surrealdb/issues/30#issue-1335459899

It would be great if there were a backup() and restore() method in the js library. Since I use firebase functions to run CRON jobs and other tasks against my surrealdb instance, it would be nice to also be able to schedule regular backups from there as well. The backup() method would simply return the .surql file and the restore() method would... restore it.
It would also be super-helpful for backing-up/restoring from a front end environment (like an administration dashboard, etc.)

**Comment by kearfy** [comment]
Hi @ntorrey, this feature is not yet implemented in the WebSocket protocol just yet, so we won't be implementing this just yet. I will leave this issue open however for when this does become an option!

**Comment by ntorrey** [comment]
Silly me - this functionality is already possible for me using the /export and /import REST endpoints! Not sure why I didn't think of this before.
In any case, I think this feature would still be useful.
If anyone else is using firebase functions and wants to know how I scheduled regular backups and got imports working, just ping me.

**Comment by kearfy** [comment]
The next release of the SDK will include an `.export()` method, imports can be done via the normal `.query()` method

**Comment by ntorrey** [comment]
🎉
