### ISSUE TITLE
change authenticate to return true false rather than throw an error ?

### ISSUE THREAD

**Issue by happysalada** [surrealdb/surrealdb.js#149]
Would you consider changing the return type of authenticate to true/false rather than throwing an error.

The reason this can be problematic, is that for example in a framework like sveltekit, redirection is done using a throw. This complicates the logic quite a bit.

I know this would be a breaking change, so I would understand if it's not possible, just thought I might ask.

**Comment by kearfy** [comment]
Hi! Returning just `false` instead of throwing an error will potentially cover up the reason for authentication failure.

That said, you could catch any thrown errors and return `false` yourself:
```ts
const token = await db.signin({ 
    // I'm using root auth as an example here. 
    // The same principle applies to ns/db/sc signin, or the signup/authenticate functions.
    user: 'root', 
    pass: 'root' 
})
    // Make sure value is a string and not undefined
    .then((v) => v ?? false as false)
    // Return false for any thrown errors
    .catch(() => false as false);

    // I strongly typed false as false here because later on we probably want to check just for `false`.
    // If not, the type will be `string | boolean`.
    // If you want cleaner code, return `undefined` in the`.catch()` function. 
    // That way you can drop the `.then()` function and still simply check if the value is truthy
```

With this, you will be left with either a type like `string | false`.
Let me know if that works for you!

**Comment by happysalada** [comment]
I was thinking of the authenticate method actually.
That is the one that will mostly be used after the initial signin.
That method returns nothing.
I've usually got something like this on the server

```
  try {
    await db.authenticate(jwt);
    let databaseResults = await db.query(
      `
SELECT * FROM user WHERE id = $user;
SELECT * FROM daily_rate WHERE time::floor(created_at - 5h, 1d) = time::floor(time::now() - 5h, 1d) ORDER BY created_at DESC FETCH from_currency, to_currency;
`,
      { user: user_id }
    );
    return { databaseResults };
  } catch (e) {
    console.log(e);
    throw redirect(303, '/signin');
  }
```

but most likely the authenticate error should be handled differently than the query error. That's why I was thinking of using the return part of the authenticate function to try to do something different.
This is coming from sveltekit.
catching the authenticate is fine, but the then part is falsy as well.
How about just returning true in case authentication is successfull ?

I could also add a small try catch around the authenticate to try to handle this case in a particular way. It's more boilerplate, but it's more correct. Somehow I'm wishing for something a little more elegant, but maybe that's as beautiful as it gets with typescript.

**Comment by kearfy** [comment]
Ah, yes! It indeed makes sense to return true for the `.authenticate()` function! I will patch this up soon along with some other changes for a `v0.9.0` release!

**Comment by happysalada** [comment]
Could it also not `throw` as well ? (if possible)
In order to handle the unauthenticated case a little more gracefully.

**Comment by kearfy** [comment]
`throw` is made just for that, so I won't remove it. I will probably make it optionally graceful when you pass a token to the `.connect()` function, as this is something you currently cannot really get around :)

**Comment by happysalada** [comment]
So the correct way to handle authentication before the 0.9.0 release is
```
  const authenticated = await db.authenticate(jwt).then(() => true)
    .catch((e) => {
      console.log(e);
      return false
    })
  if (!authenticated) throw redirect(303, '/signin');
```
(this is with sveltekit that uses throw to redirect).
and after it should be something like
```
  const authenticated = await db.authenticate(jwt).then((response) => response)
    .catch((e) => {
      console.log(e);
      return false
    })
  if (!authenticated) throw redirect(303, '/signin');
```

Just want to make sure I understand correctly.

**Comment by kearfy** [comment]
Yep! That's a way to tackle it!

**Comment by wedobetter** [comment]
1. [Surreal.connect](https://github.com/surrealdb/surrealdb.js/blob/main/src/strategies/websocket.ts#L47) should be an async function otherwise we cannot catch exceptions

```javascript
try {
   new Surreal("wss://xyz.com/rbc", {auth: {pass: "wrongPassword"}})
} catch {
    ...
}

// call inside connection is async and is thrown outside the try block. 
```

2. new Surreal(), should not call connect automatically
