### ISSUE TITLE
Promise in "send" never resolve

### ISSUE THREAD

**Issue by Nainterceptor** [surrealdb/surrealdb.js#153]
When I'm trying to connect, without running database, in deno, with top-level await, I've an error "Top-level await promise never resolved".

---

In the `send` method of the `WebSocketStrategy` class:

```typescript
protected send<T = unknown, U = Result<T>>(
    method: string,
    params?: unknown[],
) {
    return new Promise<U>((resolve) => {
        if (!this.socket) throw new NoActiveSocket();
        this.socket.send(method, params ?? [], (r) => resolve(r as U));
    });
}
```

The promise is resolved when the `this.socket.send` method's callback is invoked. However, if an error is thrown, such as when there is no active socket (`if (!this.socket) throw new NoActiveSocket();`), the promise is never resolved or rejected. This can lead to hanging promises, which can be problematic, especially when using top-level `await` in TypeScript.

For example, with top-level `await` in TypeScript:

```typescript
import Surreal from "https://deno.land/x/surrealdb@v0.8.3/mod.ts";
const connection = new Surreal(`http://localhost:8000/rpc`);
await connection.signin({
  user: 'root',
  pass: 'root',
});
console.log("hello world");
```

-> Try to run this script with `deno run --allow-net test.ts` without database running

If the `send` method throws an error, the `console.log` statement might never get executed because the promise is neither resolved nor rejected.

### Root Cause:

The root cause of this issue is that the promise created in the `send` method does not have a rejection path for errors. When an error is thrown inside the promise executor function, the promise remains pending indefinitely.

### Solution:

To address this issue, you should add a rejection path for the promise. This can be done by wrapping the code inside the promise executor function in a try-catch block and rejecting the promise in the catch block (but it's not elegant):

```typescript
protected send<T = unknown, U = Result<T>>(
    method: string,
    params?: unknown[],
) {
    return new Promise<U>((resolve, reject) => {
        try {
            if (!this.socket) throw new NoActiveSocket();
            this.socket.send(method, params ?? [], (r) => resolve(r as U));
        } catch (error) {
            reject(error);
        }
    });
}
```

By adding this rejection path, any errors thrown inside the promise will cause the promise to be rejected, preventing hanging promises and ensuring that errors are properly propagated.

**Comment by kearfy** [comment]
Hiya! This is not actually caused by the promise not being rejected, in fact, the throw statement you are referring to is not even invoked 😅 

This issue is rather caused by the library not handling any errors from the websocket (it will throw an error which states that the connection was refused, but through an eventListener)

Will work out a solution soon, thanks for bringing this to our attention!

**Comment by Nainterceptor** [comment]
Uhu, sorry for the mistake, I'm working with Deno + Fleet recently, and I don't have yet a great debugger...

Thanks !

**Comment by kearfy** [comment]
No problem! It took me a few minutes to connect the dots aswell! Haha. Enjoy your evening!

**Comment by kearfy** [comment]
Looked a little bit further into this, but it will need a bit of a refactor in promise handling (which is an improvement in this case).
Will work on it soon, just not at the moment as there are some more pressing priorities :)
