### ISSUE TITLE
Bug: NextJS 13 (app router) with Node and Surreal

### ISSUE THREAD

**Issue by leolorenzoluis** [surrealdb/surrealdb.js#156]
### Describe the bug

I'm getting the following and I'm not sure what causes it. I'm using SurrealDB 0.8.3. This is only when it's trying to instantiate and call the db client

```
Module not found: Can't resolve 'bufferutil' in '/Users/meh//node_modules/ws/lib'

Import trace for requested module:
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/receiver.js
./node_modules/ws/wrapper.mjs
./node_modules/unws/src/node.mjs
./node_modules/surrealdb.js/esm/library/WebSocket/node.js
./node_modules/surrealdb.js/esm/library/SurrealSocket.js
./node_modules/surrealdb.js/esm/strategies/websocket.js
./node_modules/surrealdb.js/esm/index.js
./db.ts
./auth.ts
./app/api/auth/[...nextauth]/route.ts

```

### Steps to reproduce

```
export const getDbClient = async () => {
    await db.signin({
        user: 'bla',
        pass: 'blah'
    });
    await db.use({ ns: test', db: 'test' });
    return db;
}
```

### Expected behaviour

It should not throw

### SurrealDB version

Release v1.0.0-beta.9

### SurrealDB.js version

0.8.3

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Hi Leo, 

This is not something we can solve, but there is an easy workaround: https://github.com/vercel/next.js/issues/44273

Simply adjust the config of webpack in your `nextjs.config.js` file to include the following bit (provided a complete config file as example):
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
    webpack: (config) => {
        config.externals.push({
            'utf-8-validate': 'commonjs utf-8-validate',
            bufferutil: 'commonjs bufferutil',
        });
        return config;
    },
};

module.exports = nextConfig;
```

Let me know if this helps!
Micha

**Comment by leolorenzoluis** [comment]
Amazing find i tried searching it didn’t come up. You have better google skills than me! Thank u

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
