### ISSUE TITLE
Bug: Cant pass NONE value to MERGE object to unset fields

### ISSUE THREAD

**Issue by hchockarprasad** [surrealdb/surrealdb.js#163]
### Describe the bug

How to unset a field via `UPDATE tb MERGE {...}` object.? JSON doesn't support this . Do we have a workaround for this?

### Steps to reproduce

```
{
    "data": {
        "opt_name": NONE
    }
}
```

### Expected behaviour

Need a way to unset fields via object

### SurrealDB version

v1.0.0-beta.11

### SurrealDB.js version

0.8.4

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Hi @hchockarprasad, I'm afraid you will need to use a custom query for this sort of mutation!

**Comment by kearfy** [comment]
This should be resolved by #227, `undefined` will now be considered `none`
