### ISSUE TITLE
Bug: NoActiveSocket: No socket is currently connected to a SurrealDB instance. Please call the .connect() method first!

### ISSUE THREAD

**Issue by happysalada** [surrealdb/surrealdb.js#167]
### Describe the bug

first of all the Connection.connect type is not a promise. in the readme it says `await db.connect()` but the connect type is a function that returns void.

Second of all, I'm on surreal-1.0.0-beta.9 and when trying to connect with the library 0.9 it just throws the error 
```
NoActiveSocket: No socket is currently connected to a SurrealDB instance. Please call the .connect() method first!
```
my code is exactly like 
```
    const db = new Surreal();
    await db.connect(`${SURREAL_URL}/rpc`);
```

do I need a specific version of surreal running on the server ?
could you update the connect type to be a promise?

### Steps to reproduce

```

    const db = new Surreal();
    await db.connect(`${SURREAL_URL}/rpc`);
```

### Expected behaviour

no error thrown when trying to connect

### SurrealDB version

1.0.0-beta.9

### SurrealDB.js version

0.9.0

### Contact Details

happysalada@tuta.io

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Micnubinub** [comment]
I'd say update to `Surreal 1.0` and check there as this may already be resolved.  `SurrealDB.js 0.9` changed some methods functions too... **Make sure you backup you data first** as the data from `Beta 9` isn't compatible with newer versions (import after upgrading) check this page [Upgrading](https://surrealdb.com/docs/installation/upgrading/beta9-to-beta10)

**Comment by happysalada** [comment]
I've upgraded to surreal 1.0 and I still get the same error.
here is the code I'm using
```
    const db = new Surreal();
    // TODO wrap in try catch
    await db.connect(`${SURREAL_URL}/rpc`);
    const authenticated = await db.authenticate(jwt).then(() => true)
      .catch((e) => {
        console.log(e);
        return false
      })
```

could you also at least update the type for connect to return a promise (so that await in front won't generate a typescript warning).

**Comment by happysalada** [comment]
and downgrading back to 0.8.4 the signup doesn't work
```
Error: There was a problem with the database: The signup query failed
    at WebSocketStrategy.signup (file:///Users/raphael/dev/mono_sweif/node_modules/.pnpm/surrealdb.js@0.8.4/node_modules/surrealdb.js/esm/strategies/websocket.js:166:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (/Users/raphael/dev/mono_sweif/apps/brocop/src/routes/(auth)/signup/+page.server.ts:42:17)
    at async Module.handle_action_json_request (/Users/raphael/dev/mono_sweif/node_modules/.pnpm/@sveltejs+kit@1.25.0_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:57:16)
```

**Comment by happysalada** [comment]
I've found the problem with the socket currently connected, but I can't make the signup function work.

**Comment by happysalada** [comment]
so here is my code for signup
```
    await db.connect(`${SURREAL_URL}/rpc`, {
      ns: SURREAL_NAMESPACE,
      db: SURREAL_DATABASE,
    })

    try {
      let jwt = await db.signup({
        NS: SURREAL_NAMESPACE,
        DB: SURREAL_DATABASE,
        SC: 'end_user',
        name: form.data.name.trim(),
        phone: form.data.phone,
        email: form.data.email.trim(),
        password: form.data.password.trim()
      });
```

I've also tried modifying the connect to include root user and password

on the side of the database, the signup function didn't change between beta.9 and 1.0.0

```
scopes: {
                        admin: 'DEFINE SCOPE admin SESSION 1d SIGNIN (SELECT * FROM admin WHERE email = $email AND crypto::argon2::compare(password, $password))',
                        end_user: 'DEFINE SCOPE end_user SESSION 1d SIGNUP (CREATE user SET email = $email, password = crypto::argon2::generate($password), name = $name, phone = $phone) SIGNIN (SELECT * FROM user WHERE email = $email AND crypto::argon2::compare(password, $password))'
```

**Comment by happysalada** [comment]
The error on signup was caused by a switch of default value from `VALUE time::now()` to `DEFAULT time::now()`

I've made a comment on the last commit where the type for connect should be changed, but appartt from that, the issue is a non issue.

**Comment by kearfy** [comment]
It is interesting though how that results in this error. A faulty schema should rather result in an authentication failure..

**Comment by happysalada** [comment]
No the error was something else. It was my bad there qas 2 places i was calling surreal and it was in the other place. The faulty schema just causes typescript to complain.
