### ISSUE TITLE
question: bun runtime; `ws` or native `WebSocket`

### ISSUE THREAD

**Issue by mathe42** [surrealdb/surrealdb.js#17]
As discussed in disscord the bun runtime is currently supported. We should investigate if it loads the `ws`-package for WebSockets or the native implementation in bun.

**Comment by Choooks22** [comment]
Wow, did some investigation and it turns out it would resolve `ws` from `isomorphic-ws`, but `ws` is patched to export bun's native websocket object. :rocket:

From an empty directory without `ws` installed, run this:

```ts
import { WebSocket } from 'ws'

console.log(WebSocket)
```

**Comment by mathe42** [comment]
close this as resolved
