### ISSUE TITLE
Bug: Not working on an IDE with Nix like Replit?

### ISSUE THREAD

**Issue by JakeAsunto** [surrealdb/surrealdb.js#170]
### Describe the bug

![IMG_20230922_145610](https://github.com/surrealdb/surrealdb.js/assets/119887532/dfe2f579-6df5-472b-bc10-4c173d37ee47)

### Steps to reproduce

i just made an index.js file on replit and just copy pasted the code in the nodejs sdk docs and it seems to appear like this when i run it...

### Expected behaviour

I would expect it to start the db server and listen for queries. any solutions to this?

### SurrealDB version

latest

### SurrealDB.js version

0.9.0

### Contact Details

asuntojake3@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakeAsunto** [comment]
idk if this is due to my noobness but i just tested it out and just copied the code from the replit docs like this
![IMG_20230922_150049](https://github.com/surrealdb/surrealdb.js/assets/119887532/774033f1-900a-4ffd-87dc-f48605d88132)
![IMG_20230922_150102](https://github.com/surrealdb/surrealdb.js/assets/119887532/29544cb8-8ac0-4eb4-abcb-4c2472461825)

**Comment by maycontainweasel** [comment]
For anyone else reading, i can't be 100% sure if this is actually the solution, but when i tried running surrealdb.js 0.9 on node v16, it gave me the same error. When i switched node over to v20 with NVM, it started working.
