### ISSUE TITLE
Feature: Allow getting & validating signin token without authenticating token

### ISSUE THREAD

**Issue by LeoDog896** [surrealdb/surrealdb.js#177]
### Is your feature request related to a problem?

I'm making an internal implementation of an SSR-compatible SurrealDB library that allows the client to connect directly to the DB and the server to pre-render content and allow non-JavaScript environments to use the application.

I'm currently adding sign-in logic, and I would like the _client_ to be able to use `signin`, but I want the server to simply set the cookie for the user and validate it for specific methods.

### Describe the solution

Adding an extra two methods allows for getting the token of authentication when signing in to a scope and for getting the database entry from a token.

### Alternative methods

For the first one, I could use the HTTP endpoint [/signin](https://surrealdb.com/docs/integration/http#signin). I have no clue on how do to the latter. 

### SurrealDB version

1.0.0+20230913.54aedcd for windows on x86_64

### SurrealDB.js version

0.9.1

### Contact Details

leodog896@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by woodmark-dev** [comment]
Hello
Can I get an opportunity to work on this issue? I'm very much interested in this project, and I'm very familiar with node.js. Thank you.

**Comment by akankshadharkar** [comment]
@woodmark-dev yes, please feel free to take this up if you're interested in it. We'd be glad to help out if you need any assistance! ^_^

**Comment by kearfy** [comment]
Hi @LeoDog896, as for retrieving the currently authenticated user's record, we have the `.info()` method. @woodmark-dev I think we track the token internally already, we can simply add a method to return that token when invoked. Feel free to open a PR for that, thanks!

**Comment by kearfy** [comment]
Oh, to add @LeoDog896, the `.signin()` and `.signup()` methods currently already return a token for the authenticated user. The types for the `.signin()` methods need to be adjusted to always return a string (the token), as root users now also get back a token. This means that you will either receive a token, or an error will be thrown 😁

**Comment by LeoDog896** [comment]
> We have the `.info()` method for retrieving the currently authenticated user's record.

Absolutely! However, that requires authenticating the current-scope, but since I'm doing this server side, I don't want to authenticate the server-side connection with this user scope - I would like to be able to query it without mutating the authentication state of the current connection.

**Comment by LeoDog896** [comment]
Not in that full scope, but essentially a dry-run signin/signup query, and the ability to use those signin/signup queries in requests. The actual (name pending) `tryQuery` method itself isn't a dry run, but an authenticated request from those dry-run signin/signup queries.

**Comment by kearfy** [comment]
Okay, so purely about auth. I would honestly rather suggest just to open a new connection to validate auth and to close it afterwards. The `.authenticate()` method will return `true` if successful (note that the experimental HTTP client does not validate the token, the WS client does). You can optionally also use the `.info()` method to select the data from the scope user's record.

Selecting should not trigger any updates, unless you are doing complex logic with futures :)
