### ISSUE TITLE
Feature: Tagged Template Literals

### ISSUE THREAD

**Issue by MatthewAry** [surrealdb/surrealdb.js#185]
### Is your feature request related to a problem?

Query injection attacks is a known problem for databases and the conventional methods to handling them add friction to the developer experience. There is a feature in JavaScript called Tagged Template Literals. It would be nice if support for them can be added into the JS, Node, and Deno SDKs.

### Describe the solution

See:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates
- https://neon.tech/blog/sql-template-tags

### Alternative methods

N/A

### SurrealDB version

1.0.0+20230913.54aedcd for macos on x86_64

### SurrealDB.js version

1.0.0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LucyEgan** [comment]
+1 for this but it seems a fine line for people to accidentally do .query(``) instead of .query`` and loose the benefit so maybe it's own method that only accepts string template variables?

**Comment by kearfy** [comment]
This is on my todo list actually! I'm planning on doing an implementation where a tagged template literal would basically be a prepared query, which you can pass to the `.query()` function 😃 

```js
await db.select(surrealql`SELECT * FROM ${data}`)
```
