### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by mathe42** [surrealdb/surrealdb.js#19]
Update the docs on www.surrealdb.com (combine deno, node, browser into 1 page) also add bun runntime

**Comment by oberbeck** [comment]
Personally, I like to have documentation close to the source.

From what I can tell, currently, the documentation is in the website's repository. Does someone have an idea/strategy in mind how to proceed?

**Comment by VixieTSQ** [comment]
> Personally, I like to have documentation close to the source.
> 
> From what I can tell, currently, the documentation is in the website's repository. Does someone have an idea/strategy in mind how to proceed?

This is why I love rust... doc comments are awesome! I don't believe there is an equivalent in JS/TS. The next best thing is we should at least have examples inside the README. We can even really just copy&paste from docs on the website. It's better than nothing.

**Comment by tobiemh** [comment]
Docs on the readme is good 👍 . Obviously docs on the website need to be up-to-date too.

**Comment by mathe42** [comment]
Yes we have #23 but I want to leave a statement regarding all docs:

1. I will work on JSDocs comments 
2. I think here in readme it is enough to add how to install it for browser, deno, node etc. + minimal example and link to docs.
