### ISSUE TITLE
Feature: .open()

### ISSUE THREAD

**Issue by timyourivh** [surrealdb/surrealdb.js#196]
### Is your feature request related to a problem?

We can close the connection with `.close()` but we're not able to open the same connection (with the same credentials) again after closing it. 
If we want to we would need to use `.connect()` again, but this method requires an url and resets the authentication, so you'd have to call `.signin()` or `.authenticate()` after that. This is secure data I (and probably others) store inside an .env file, which we'd have to obtain again.
If I log the instance after closing I can see that it has the jwt and the url so why not add a method that allows us to open the same connection.

### Describe the solution

Add a method `.open()` which does the opposite of `.close()`. It should take no params and just re-open the connection that is configured inside the instance.

Or

Allow us to call `.connect()` again without required url and preserve the credentials inside the instance.

### Alternative methods

Described in problem:

1. call `connect()` again with url
2. call `signin()` or `authenticate()` again with credentials

### SurrealDB version

1.0.0+20230913.54aedcd for linux on x86_64

### SurrealDB.js version

0.11.0

### Contact Details

timyourivh@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timyourivh** [comment]
I replaced `surrealdb.js` with `surrealdb.node` which was more suitable for the context I'm using it in. This solved my problem as I don't have to close the connection to free the terminal.

**Comment by ralyodio** [comment]
how do we close a db?
