### ISSUE TITLE
Bug: Can't connect to surreal with deno

### ISSUE THREAD

**Issue by finalclass** [surrealdb/surrealdb.js#199]
### Describe the bug

This is how I start surrealdb
![image](https://github.com/surrealdb/surrealdb.js/assets/1343930/78985b49-4f18-4bb8-9cff-2c02c2acfe0e)

I can connect via cli:

![image](https://github.com/surrealdb/surrealdb.js/assets/1343930/2d839629-5f24-4b90-97ab-25bbcb0691ce)

However I cannot do that with the SDK:

![image](https://github.com/surrealdb/surrealdb.js/assets/1343930/157c9254-d1c7-4697-8bc8-16bd62df27d2)

### Steps to reproduce

Described above

### Expected behaviour

No authentication error

### SurrealDB version

1.0.0+20230913.54aedcdb for linux on x86_64

### SurrealDB.js version

0.11.0

### Contact Details

s@finalclass.net

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by finalclass** [comment]
```bash
root@43932fdf8ef0:/# deno --version
deno 1.37.2 (release, x86_64-unknown-linux-gnu)
v8 11.8.172.13
typescript 5.2.2
```

**Comment by finalclass** [comment]
Worth noting is that on previous versions it works fine:

![image](https://github.com/surrealdb/surrealdb.js/assets/1343930/393a8863-7207-4aa3-8908-8c620ddbea32)

**Comment by kearfy** [comment]
Hey @finalclass, we recently renamed the NS, DB, SC, user and pass properties to namespace, database, scope, username and password respectively to better align our ecosystem of SDKs. This was noted in the release notes of I believe, the v0.10.0 release 😃

Let me know if those changes work out for you

**Comment by finalclass** [comment]
Make notice that here:
![image](https://github.com/surrealdb/surrealdb.js/assets/1343930/e79d96fc-ee8d-4533-addb-3776d1e4c010)

I'm just doing what is stated in README without executing the "USE" statement.

Moreover when I execute `signin` with the new parameter names:

```
    await this.db.signin({
      user: this.dbConfig.user,
      pass: this.dbConfig.pass,
      namespace: this.dbConfig.ns,
      database: this.dbConfig.db,
    });
```

I get the same result:

![image](https://github.com/surrealdb/surrealdb.js/assets/1343930/de68de2e-4708-46e4-ab6c-7340b7f8728b)

**Comment by kearfy** [comment]
`user` -> `username`, `pass` -> `password` :)
I'll get those examples updated
