### ISSUE TITLE
test: add basic tests

### ISSUE THREAD

**Issue by oberbeck** [surrealdb/surrealdb.js#20]
Currently we are heavily refactoring the codebase and brought together the deno/JS/NodeJS code base.

From here on it makes sense to add basic code coverage to assure nothing breaks with new changes.

Decisions to make:
- ~Unit Test framework~

**Comment by mathe42** [comment]
I propose if #21 is merged this to make in deno with the deno test tools. Or something non runntime specific.

**Comment by oberbeck** [comment]
Since we want to support all the runtimes, I think it makes sense to be able to run the tests in all of them.

**Comment by mathe42** [comment]
Yes but:

Assuming all runtimes are equal with WebSockets (yes for node we nede `ws` but that is just a spec-compliant implementation). So if it works in Deno and all runtimes know if they use their nativ WebSocket or `ws` it works for all runtimes.

**Comment by oberbeck** [comment]
> Yes but:
> 
> Assuming all runtimes are equal with WebSockets (yes for node we nede `ws` but that is just a spec-compliant implementation). So if it works in Deno and all runtimes know if they use their nativ WebSocket or `ws` it works for all runtimes.

Do you still think so, especially after looking at eg: https://github.com/surrealdb/surrealdb.js/pull/29/files#diff-bee239710d6adb6ea30da43de12674e14478bb6907e5e1b2d447e12c7bcae81cL2

**Comment by mathe42** [comment]
Yes for unit test this doesn't change anything. But you might want to add type tests with different targets.

**Comment by mathe42** [comment]
I would propose to add a build - test for now...

**Comment by mathe42** [comment]
see #31

**Comment by mathe42** [comment]
Maybe an e2e test is a good idea:

Create a JS file of form:

```js
export default (client) => {
  // ...
}
```

That does a lot of client requests etc.

Than have an entry file for node, deno, bun that uses that file.

The test would be as follows:
1. Setup Node + Deno + Bun
2. Build dist folder
2. Start SurrealDB in a Docker-Container (specific version)
3. run deno script
4. export DB into file and compare that with a snapshot of that file (filecontents the same = test passed)
5. restart DB (and reset it)
6. Same for Node and Bun

**Comment by oberbeck** [comment]
> 1. Setup Node + Deno + Bun

Maybe we could put this already in a container?

> 4. run deno script

What kind of script are you thinking about?

> 5. export DB into file and compare that with a snapshot of that file (filecontents the same = test passed)

Why not use the lib itself to read from the DB?

**Comment by mathe42** [comment]
> Maybe we could put this already in a container?

This are a few lines in the github action no need for a container setup


> What kind of script are you thinking about?

A lot of stuff where you use all of the methods etc. Same script for Deno, Bun, Node just different import.


> Why not use the lib itself to read from the DB?

With a complete DB dump we can check that Node, Deno, Bun all leave the DB in the exact same state.

**Comment by oberbeck** [comment]
sounds good! I can have a look into it, or are you already on it?

**Comment by mathe42** [comment]
@oberbeck maybe you can create the script (for Node) and I create the github action etc as I have some experience with that...

**Comment by oberbeck** [comment]
> @oberbeck maybe you can create the script (for Node that we can then adopt for Deno + Bun) and I create the github action etc as I have some experience with that...

just to be clear, we are talking about the implementation of https://github.com/surrealdb/surrealdb.js/blob/bb7615506683ab5ae855a63e94faa86b2d3045bf/test/e2e/shared.js#L1-L6 correct?

**Comment by mathe42** [comment]
Maybe our snapshot can include things like `$ID$` where a random ID is included...

**Comment by mathe42** [comment]
Is it the same of you `await` each operation?

**Comment by oberbeck** [comment]
OK, seems to be some kind of async/random issue:


Deno Run 3
```
UPDATE person:8zpm55qj2wfcad78c4kn CONTENT { id: person:8zpm55qj2wfcad78c4kn, identifier: "l1nvuhot6v", marketing: true, name: { first: "Tobie", last: "Morgan Hitchcock" }, title: "Founder & CEO" };
UPDATE person:jaime CONTENT { id: person:jaime, marketing: true };
```

NodeJs Run 3
```
UPDATE person:1dksegxcz2k0sf1h0moy CONTENT { id: person:1dksegxcz2k0sf1h0moy, identifier: "a0su3u2f1c", marketing: true, name: { first: "Tobie", last: "Morgan Hitchcock" }, title: "Founder & CEO" };
UPDATE person:jaime CONTENT { id: person:jaime, marketing: true };
```
