### ISSUE TITLE
Feature: Export types used in module

### ISSUE THREAD

**Issue by OTheNonE** [surrealdb/surrealdb.js#208]
### Is your feature request related to a problem?

I want to use some of the SurrealDB.js types to define functions, in this case specifically the `LiveQueryResponse`. I find myself having to re-create the types in order to define type-safe functions using the module.

### Describe the solution

Export the types as following:
```
import { Surreal, type LiveQueryResponse } from "surrealdb.js";
```

### Alternative methods

Creating the types myself...

### SurrealDB version

surreal 1.1.1

### SurrealDB.js version

v0.11.0

### Contact Details

olavnon@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
This should be resolved by #227
