### ISSUE TITLE
Feature: Bun SDK for surrealdb

### ISSUE THREAD

**Issue by j209** [surrealdb/surrealdb.js#213]
### Is your feature request related to a problem?

bun surrealdb seamless integration

### Describe the solution

 SurrealDB SDK for [Bun](https://bun.sh/) like SurrealDB SDK for deno

### Alternative methods

sdk for node.js

### SurrealDB version

1.1

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThatOneCalculator** [comment]
Currently using `surrealdb.js` with Bun 1.1.4. No apparent issues.

**Comment by kearfy** [comment]
Closing as stale. We might work on a native module for bun in the future with support for embedded surrealdb
