### ISSUE TITLE
Feature: Parse object- and array based record ID

### ISSUE THREAD

**Issue by OTheNonE** [surrealdb/surrealdb.js#215]
### Is your feature request related to a problem?

I have the following table (shown in JS):
```
let record = {
    id: "measurement:{ date: "2024.01.01T00.00.00", device: "my-device" }"
    temperature: 23.5,
    pressure: 102456,
    humidity: 34,
}
```

I want to use the date value in this record, but find myself having to parse the `id` in order to use it. Instead, i just add a duplicate field of `date` to the record:
```
let record = {
    id: "measurement:{ date: "2024.01.01T00.00.00", device: "my-device" }"
    date: "2024.01.01T00.00.00"
    temperature: 23.5,
    pressure: 102456,
    humidity: 34,
}
```

### Describe the solution

When using object- or array based record ID's, it would be nice to have the `id` parse. It could look something like this:
```
let record = {
    table: "measurement",
    id: { 
        date: "2024.01.01T00.00.00", 
        device: "my-device" 
    },
    temperature: 23.5,
    pressure: 102456,
    humidity: 34,
}
```

In this example, the id is split into two properties, `table` and `id` which might not be preferable, but something along this way would be awesome!

### Alternative methods

Alternative methods are to parse the `id`, or add extra properties on the record.

### SurrealDB version

surreal 1.2.0 for windows

### SurrealDB.js version

0.11.0

### Contact Details

olavnon@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OTheNonE** [comment]
I notice now in [the Docs](https://docs.surrealdb.com/docs/surrealql/datamodel/ids), that they are duplicating the values, which was my workaround solution. Does it take up more space in the database by having duplicates, or does the `id` and the `date` refer to the same storage value? My overall concerns around this problem is trying to have the records sizes as small as possible in the database.

**Comment by kearfy** [comment]
Hey @OTheNonE, since the introduction of a CBOR protocol I've been working on a refreshed version of this library in the jsv2 branch, which adds native support for all SurrealQL including Record IDs. Will hopefully ship it sooner than later!

**Comment by OTheNonE** [comment]
Well awesome! Can’t wait to see the result!

**Comment by kearfy** [comment]
Hey @OTheNonE, the v1.0.0-beta.x releases now ship with a RecordId class, adding support for this functionality! 😃

**Comment by OTheNonE** [comment]
Awesome! Cant wait to try it out, thank you for your great effort💪🏻

**Comment by PlkMarudny** [comment]
Well, I have tried this, and I do not think this is the solution, for example, I have id like:
`
"story:[ 7271828433141143836, r"lists:9vo54nl1by0x8z93t6ly", 123, 1733739002499 ]"
`
RecordId class constructor requires two arguments, here: `tb' ("story")` and the id. `toJSON()` and `toString()` methods do not help much (I refer to Javascript SDK). So anyway, I need to strip `story:` first, and well, convert the string to array later on.
