### ISSUE TITLE
[BUG]: Path is ignored in the Connenction URL

### ISSUE THREAD

**Issue by N0tExisting** [surrealdb/surrealdb.js#217]
### Describe the bug

When giving a custom path into the `connect()` method it is ignored.

This is anoying because of my dev setup:
```ts
import { defineConfig } from 'vite';

export default defineConfig({
	server: {
		proxy: {
			'/db': 'http://localhost:8000/',
		},
	},
});
```

### Steps to reproduce

```ts
import Surreal from 'surrealdb.js';

const db = new Surreal();

const url = new URL(location.href);
url.pathname = '/db/rpc';
url.protocol = url.protocol === 'http' ? 'ws' : 'wss';

await db.connect(url.href, p);
```
results in:
```
SurrealSocket.ts:56  WebSocket connection to 'wss://localhost:3000/rpc' failed: 
open @ SurrealSocket.ts:56
```

### Expected behaviour

Connecting to the database should respect the path in the URL.

### SurrealDB version

unrelated

### SurrealDB.js version

0.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Hey @N0tExisting, the v1.0.0-beta.x release(s) solve this issue 😃
