### ISSUE TITLE
Bug: Argument of type 'TemplateStringsArray'  is not assignable to parameter of type 'string[]'

### ISSUE THREAD

**Issue by oliver-oloughlin** [surrealdb/surrealdb.js#221]
### Describe the bug

TypeScript complains about the argument type when using `surrealql()` as a tagged function:
![surql_error](https://github.com/surrealdb/surrealdb.js/assets/54100972/6d18a792-f309-43fd-b0ea-37891b4c751b)

Tested in Deno and a Next.js project running on Node

### Steps to reproduce

Import `surrealql` or the alias `surql` and call it as a tagged function.

### Expected behaviour

I expect calling `surrealql` as a tagged function to work without TypeScript giving errors about the input type.

### SurrealDB.js version

v0.11.0

### Contact Details

oliveroloughlin@hotmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Fixed by #222
