### ISSUE TITLE
update repository/contributor docs

### ISSUE THREAD

**Issue by oberbeck** [surrealdb/surrealdb.js#23]
In https://github.com/surrealdb/surrealdb.js/issues/19 we discuss how to document the usage of this library.
In addition, we should also have some documentation for this repository. Here, I am thinking about

- [ ] repo structure
- [x] requirements
- [x] build/dev instructions
- [x] note on supported environments

I believe this is especially needed as we are mixing Deno, NodeJS, etc. in a project which is quite unusual.

**Comment by VixieTSQ** [comment]
> repo structure

sounds like a thing solely for contributors.

> requirements

What requirements?

Could probably also add code example to the list.

**Comment by oberbeck** [comment]
> > repo structure
> 
> sounds like a thing solely for contributors.

That's what I mean - documentation for contributors. Everything else (lib user facing) I see as part of https://github.com/surrealdb/surrealdb.js/issues/19

**Comment by VixieTSQ** [comment]
> > > repo structure
> > 
> > 
> > sounds like a thing solely for contributors.
> 
> That's what I mean - documentation for contributors. Everything else (lib user facing) I see as part of #19

Ahh, the distinction between the two issues was unclear. This could probably use a better title

**Comment by oberbeck** [comment]
> What is "repo structure" for you? / What is missing to close this?

I was thinking about the usual stuff. Things like the general folder structure, naming conventions, and so on.

**Comment by VixieTSQ** [comment]
> > What is "repo structure" for you? / What is missing to close this?
> 
> I was thinking about the usual stuff. Things like the general folder structure, naming conventions, and so on.

You should probably be able to intuit all that stuff by just looking at the code. Codebases usually have a good starting point when trying to understand them, such as the `Surreal` class in this case
