### ISSUE TITLE
comment last  merged 👍 thanks for TS

### ISSUE THREAD

**Issue by matigumma** [surrealdb/surrealdb.js#24]
iv been trying last merged with typescript and get this observations:

- i think should update  "version": "0.3.1"  to 0.3.2 maybe?
- at package.json i have to change export types as:
`{
  ...,
  "types": "./dist/types/index.d.ts", ... }
`
to avoid msg at import * from  'surrealdb.js' // error: Cannot find module 'surrealdb.js' or its corresponding type declarations.

its not easy to understand the use flow (for me) 
iv been using like this at server side (nextjs api)

```
import Surreal from 'surrealdb.js';

const db = new Surreal('https://surreal...:8000/rpc');

try {
      await sdb.use('test', 'test');

      await sdb.signin({
        user: 'root',
        pass: 'root',
      })

      const r = await sdb.query('INFO FOR DB;');
      console.log(r) // successful 
} catch (e) { ... }
```
my question is,, thats ok?

what about authentication?
how to setup auth?
how about tokens?

ty in advance!

**Comment by VixieTSQ** [comment]
Version will likely be incremented once the new changes are ready to push to NPM. Pushing to npm will also probably fix the `Cannot find module` error I've been told. The code example you gave looks sane to me!

**Comment by mathe42** [comment]
We had the big PR merged yesterday but it is currently not released to npm. (For deno you can use https://raw.githubusercontent.com/surrealdb/surrealdb.js/main/mod.ts as the import to test it). 

To test this for node do the following:
1. clone this repo 
2. run `npm i`
3. run `npm run build`
4. create a new file in this folder (for example `testing.ts`) there you can import the module with `import Surreal from '.'`

**Comment by gotjoshua** [comment]
> currently not released to npm

Is there an ETA on that? Me===eager

**Comment by mathe42** [comment]
@gotjoshua was expected yesterday but somehow it wasn't. Was published to Deno but not npm... You can use `mathe42.surrealbd.js` as a drop in replacement.

**Comment by tobiemh** [comment]
SHould be published now @ NPM and DENO

**Comment by tobiemh** [comment]
@mathe42 forgot to `npm publish` 😖 .

Would be great to get `npm publish` as a GitHub workflow action whenever a tag is published in future!
