### ISSUE TITLE
Bug: Connection Unavailable with HTTP protocol in v1.0.0-beta.5

### ISSUE THREAD

**Issue by dodanex** [surrealdb/surrealdb.js#245]
### Describe the bug

Using v1.0.0-beta.5 I got this error:
`ConnectionUnavailable: There is no connection available at this moment.`

But after switching back to v0.11.1 it works fine.

**Edit from maintainer:** _In the previous SDK, the class you used decided which protocol you would connect over, meaning http would get "corrected" to websocket. There seems to be an issue with the HTTP engine, need to investigate what is going on there._

### Steps to reproduce

Use the v1.0.0-beta.5 and try to connect to the database.

### Expected behaviour

To work as expected.

### SurrealDB version

1.4.2

### SurrealDB.js version

1.0.0-beta.5

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gtwww** [comment]
The Nuxt project was working fine under `surrealdb.js@0.11.1`, but when I upgraded to the latest `surrealdb.js@1.0.0-beta.5`, I encountered an issue. The error message is as follows:

```shell
dev:  ERROR  [nitro] [unhandledRejection] There is no connection available at this moment.
dev:
dev:   at HttpEngine.rpc (node_modules/.pnpm/surrealdb.js@1.0.0-beta.5/node_modules/surrealdb.js/src/library/engine.ts:315:10)
dev:   at runNextTicks (node:internal/process/task_queues:60:5)
dev:   at listOnTimeout (node:internal/timers:540:9)
dev:   at process.processTimers (node:internal/timers:514:7)
dev:   at Surreal.ping (node_modules/.pnpm/surrealdb.js@1.0.0-beta.5/node_modules/surrealdb.js/src/surreal.ts:160:21)

dev:  ERROR  [nitro] [unhandledRejection] There is no connection available at this moment.
dev:
dev:   at HttpEngine.rpc (node_modules/.pnpm/surrealdb.js@1.0.0-beta.5/node_modules/surrealdb.js/src/library/engine.ts:315:10)
dev:   at Surreal.ping (node_modules/.pnpm/surrealdb.js@1.0.0-beta.5/node_modules/surrealdb.js/src/surreal.ts:160:21)
```

I noticed that the client connection method in the documentation remains the same. I'm not sure if it's a compatibility issue with other dependencies.

Steps to reproduce
pnpm update surrealdb.js

Expected behaviour
The project was working fine under surrealdb.js@1.0.0-beta.5

**Comment by kearfy** [comment]
Hey @dodanex and @gtwww, could you both share how you initiate the connection to SurrealDB with the library? I'll see if I'm able to reproduce this issue

**Comment by gtwww** [comment]
@kearfy @dodanex Got it! Changing the connection url from http://localhost:8000/rpc to ws://localhost:8000 it's working fine now.

**Comment by kearfy** [comment]
Ah! It should still work via HTTP aswell however 🤔 
I'll reopen and adjust the title for the moment, need to investigate why that is happening...
Thanks!
