### ISSUE TITLE
Feature: Missing .upsert(

### ISSUE THREAD

**Issue by LucyEgan** [surrealdb/surrealdb.js#285]
### Is your feature request related to a problem?

New `UPSERT` statement was added to surreal 2.0 alpha 1, but is missing from the JS SDK

### Describe the solution

Add `db.upsert(` as a method

### Alternative methods

Run the query directly
`db.query(UPSERT...`

### SurrealDB version

2.0.0-alpha.1 for linux on x86_64

### SurrealDB.js version

1.0.0-beta.9

### Contact Details

lucy.e@aspirecomps.co.uk

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by barel-mishal** [comment]
Hi I am using upsert with tagged template and its not work to someone is working?
