### ISSUE TITLE
Bug: console.log() in authentication method

### ISSUE THREAD

**Issue by ntorrey** [surrealdb/surrealdb.js#319]
### Describe the bug

It looks like a console.log() was left in the convertAuth method here:
https://github.com/surrealdb/surrealdb.js/blob/d4dd76b6d9438023b9639d75c09e50db3f8dee00/src/types.ts#L52

It was added in the following commit:
4fd74e4843c2599865aa7634385499817d334407

### Steps to reproduce

Log in and the authentication details will be logged to the console.

### Expected behaviour

Authentication details should not be logged to the console.

### SurrealDB version

surrealdb-2.0.0-alpha.7

### JavaScript SDK version

1.0.0-beta.19

### Contact Details

via this github issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Sorry about that! Will get it removed 😅

**Comment by kearfy** [comment]
@ntorrey I added a linting rule which will prevent this from happening in the future!
