### ISSUE TITLE
Release new version to fix #320

### ISSUE THREAD

**Issue by lkwr** [surrealdb/surrealdb.js#327]
### Describe the bug

Credentials are logged everytime the backend starts. This bug is fixed in #320 but please release a new version with this fix!

### Steps to reproduce

Just connect to a database.

### Expected behaviour

Release a new version including the fix.

After fixing such a security related bug a release should happen immediately. This bug exists now for over 3 weeks. Please release a new version that can not be a big effort.

### SurrealDB version

surreal 1.5.4 for macos on aarch64

### JavaScript SDK version

1.0.0-beta.19

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Hey @lkwr, I was waiting for potentially more stuff to be included but I'll do a release now 👍
