### ISSUE TITLE
Bug: surrealdb adds nodejs as a dependency

### ISSUE THREAD

**Issue by zvictor** [surrealdb/surrealdb.js#329]
### Describe the bug

surrealdb has `isows` as dependency, which depends on `ws`, which depends on nodejs code:

> surrealdb -> isows -> ws -> nodejs

`isows` is supposed to detect the environment in a smart way, but it first [imports `ws` unconditionally](https://github.com/wevm/isows/blob/b81c110ca748c8aec18f79565bc626d3c59d35ad/src/index.ts#L1) (wtf?):

This can go unnoticed in environments that do not actually run the `ws` code, but can be a problem in more strict ones.

I have been trying to deploy a project to Cloudflare Workers using SST-ion and, there, `ws` is not accepted.

This issue has been discussed with the SST developers as well: [discord message](https://discord.com/channels/983865673656705025/1177071497974648952/1273324119206662185)

### Steps to reproduce

1. Start an [SST-ion project with Cloudflare](https://ion.sst.dev/docs/start/cloudflare/trpc/).
2. Add `surrealdb` as dependency.
3. Run `sst dev`

Alternatively, [check my reproducible (commit 17faf94)](https://github.com/zvictor/bundle-bug/tree/17faf9414bd21946d6ff983086a4ed2ebb3d1dd2) containing the steps above.

### Workaround

If we [kill `isows`](https://github.com/zvictor/bundle-bug/blob/ef1522fbf967318ee44513d375e9a717823a669f/sst.config.ts#L22-L36), the deployment works fine. However, using esbuild plugins disables SST's hot reload on dev mode.

### SurrealDB version

irrelevant

### JavaScript SDK version

1.0.0-beta.20

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Hey @zvictor, the `isows` does not actually import the `ws` dependency unconditionally. The `exports` property in their `package.json` file dictates if the "index" file or "native" file gets imported, which is how it achieves it's functionality: https://github.com/wevm/isows/blob/b81c110ca748c8aec18f79565bc626d3c59d35ad/src/package.json#L22-L30

This might be an issue in SST, but I'm not sure about it. I don't have time to look into this right away, but I hope this gives some initial clues

**Comment by zvictor** [comment]
That's a good point! I had checked their `./package.json` but didn't notice a `./src/package.json` as well. My bad!
If proper `exports` are defined, I believe its the bundler responsability to filter out non desirable files.

I will bring this question back to SST developers (we have been discussing this issue on their Discord).

**Comment by zvictor** [comment]
There is a need for changes in both `isows` and SST, but there is nothing to be done here.

Thanks for the help and all the hard work @kearfy !

**Comment by kearfy** [comment]
Amazing @zvictor, thank you!
