### ISSUE TITLE
Live Query support

### ISSUE THREAD

**Issue by wedobetter** [surrealdb/surrealdb.js#331]
### Describe the bug

error: **Live Query was made, but is not supported** 

Surrealist giving the same error

can you please confirm when this will be supported by both DB and JS SDK. Thank you!

### Steps to reproduce

await db.live

### Expected behaviour

Receive data

### SurrealDB version

2.0.0.alpha10

### JavaScript SDK version

1.0.0.beta20

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Luxbit** [comment]
I have been trying to figure out for the last 2 days, what is going on with the live queries.

1. The SDK documentation is not update to date:
`async db.listenLive<T>(queryUuid, callback)` was renamed to `async db.subscribeLive<T>(queryUuid, callback)`

2. `subscribeLive` is working fine when running SurrealDB as a backend service. I tested on `2.0.0-alpha.9 for linux on aarch64`. This works fine in memory or when using SurrealKV as a storage backend

3. Trying to embed it in Node.js is where I'm currently running into trouble. `subscribeLive` seems to be working fine, but it does NOT fire on any other action than `CLOSE`.  This problem occurs in both in memory or with SurrealKV

Here is a little test case:
```typescript
import Surreal, { LiveHandlerArguments } from "surrealdb";
import { surrealdbNodeEngines } from "./lib-src/embedded.ts";

async function run(endpoint) {
	const surreal = new Surreal({
		engines: surrealdbNodeEngines(),
	});

	console.log(
		"connecting " + endpoint,
		await surreal.connect(endpoint, { versionCheck: false })
	);

	console.log(
		"using " + endpoint,
		await surreal.use({ namespace: "test", database: "test" })
	);

	let uuid = await surreal.live("test");
	console.log("new listener: ", uuid);

	console.log("subscribing to listener ", uuid);
	await surreal.subscribeLive(
		uuid,
		(...[action, result]: LiveHandlerArguments) => {
			console.log("EVENT", action, result);
		}
	);
	console.log("triggering event", await surreal.create("test", { val: 42 }));

	setTimeout(async () => {
		console.log("closing " + endpoint, await surreal.close());
	}, 10000); // waiting 10 seconds for the event
	
}

run("mem://");
```

**Comment by wedobetter** [comment]
Apologies, I got it to work using websocket, the fact that the new JS API is all documented made me think that it already worked. I am just waiting for JS SDK v1 to be ready so that I don't have to manage it separately with Websocket's.

**Comment by mirsella** [comment]
hey, how did you use web socket ?

**Comment by Luxbit** [comment]
> hey, how did you use web socket ?

You need to spawn surrealdb as a second process and expose a port and connect to it using a local ws connection. This doesn't really fix live queries in embedded, but it is a viable workaround for now.

**Comment by mirsella** [comment]
like putting ws:// in front the url ? i tried but I still had problems.

**Comment by Jonovono** [comment]
Dang, @Luxbit so live queries still don't seem to work in embedded :(

**Comment by Luxbit** [comment]
I haven't tried if this has been fixed yet. I'm still running it by manually spawning a separate process.

Live queries are certainly intended to work in embedded.

**Comment by Jonovono** [comment]
@Luxbit ya, seems like it should
