### ISSUE TITLE
Bug: when will these be published to npm?

### ISSUE THREAD

**Issue by starascendin** [surrealdb/surrealdb.js#339]
### Describe the bug

npm versions are old, latest should be 1.0.0

### Steps to reproduce

npm versions are old, latest should be 1.0.0

### Expected behaviour

1.0.0 be published on npm

### SurrealDB version

2.0.0

### JavaScript SDK version

1.0.0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lkwr** [comment]
The version `1.0.0` is already available on npm ([see here](https://www.npmjs.com/package/surrealdb/v/1.0.0)).

Please make sure that you use the npm package with the name `surrealdb` instead of `surrealdb.js` as it was recently renamed.

**Comment by kearfy** [comment]
Closing this as the SDK is now available on NPM: https://www.npmjs.com/package/surrealdb
