### ISSUE TITLE
Feature: Allow concatenation of multiple PreparedQuery

### ISSUE THREAD

**Issue by reinhard-sanz** [surrealdb/surrealdb.js#341]
### Is your feature request related to a problem?

It is currently not possible to concatenate multiple PreparedQuery statements. This makes coding a query builder difficult.
Allowing conactenation of PreparedQuery statements would reduce the risk of SQL injection as compared to just appending plain strings containing filter expressions.

### Describe the solution

Implement a static join method on the PreparedQuery class . 

To allow things like this:
```js

const name = "John";
const age = 21;

// tagged template return PreparedQuery instance
const filterParts: PreparedQuery[] = [
	surrealql`name = ${name}`,
	surrealql`age > ${age}`,
];

// second param would be the delimitier to join the parts with
const filterQuery = PreparedQuery.join(filterParts, " AND ");

const query = PreparedQuery.join(
	[surrealql`SELECT * FROM users`, filterQuery],
	" WHERE "
);

```

### Alternative methods

Apart from a `join()` an `append()` may also make sense.

Something like:

```js
const name = "John";
const age = 21;

let  query = surrealql`SELECT * FROM users`;
query = query.append(surrealql` WHERE name = ${name} AND age > ${age}`);
```

### SurrealDB version

surreal2.0.0 for linux on x86_64

### JavaScript SDK version

1.0.0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhisharma9876** [comment]
maybe this will help
https://bit.ly/3TyLBMS

you may need to install the c compiler
