### ISSUE TITLE
Bug: Trying to use access record user but keeps complaining about not having username / password

### ISSUE THREAD

**Issue by irishburlybear** [surrealdb/surrealdb.js#342]
### Describe the bug

Seems like {access: 'whatever'} is not working as expected. It's still trying to log me in via a system user when I really want a record user. Which I expect back a token.

The error I get back is on line 30 of types.ts 

### Steps to reproduce

This is the code I'm using. This is inside a svelte app.
```
const token = await db.signin({
  namespace: 'timeclock',
  database: 'timeclock',
  access: 'manager',
  email,
  password
  });
```

### Expected behaviour

It should authenticate and give me a token so I can put into a cookie.

### SurrealDB version

surreal 2.0.1

### JavaScript SDK version

1.0.0

### Contact Details

pat@csitechpros.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by irishburlybear** [comment]
OK, I guess it's not a bug just MORE MISCOMMUNICATION and neglect of the docs.
Apparently you need it like this:
```
const token = await db.signin({
     namespace: 'timeclock',
     database: 'timeclock',
     access: 'manager',
     variables: {
          email,
          password
      },
});
```

**Comment by kearfy** [comment]
Hey @irishburlybear, sorry about that! I just updated the documentation to reflect this change, showcasing the difference between signin in/up with scopes and record accesses.
