### ISSUE TITLE
Feature: Invoking new StringRecordId with a passed StringRecordId throws an error

### ISSUE THREAD

**Issue by knackstedt** [surrealdb/surrealdb.js#372]
### Is your feature request related to a problem?

In cases where code is shared across components and some data comes through different routes, database methods may get provided an `id` object that's already a StringRecordId or a plain string inconsistently. This would lead to constant type / instance checking wherever it's used.

### Describe the solution

I propose doing a basic instance check inside of the constructor of StringRecordId. See the following PR (will link in a comment) 

### Alternative methods

Make the constructor invoke the .toString method of the provided argument. This would work though could have unintended consequences.

### SurrealDB version

2.0.4 for linux on x86_64

### JavaScript SDK version

1.0.6

### Contact Details

knackstedt@outlook.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Closing this now as this issue is now fixed on main
