### ISSUE TITLE
db.select incorrectly throws when id is not found

### ISSUE THREAD

**Issue by auroraisluna** [surrealdb/surrealdb.js#43]
Using `db.select("some id that doesn't exist")` will throw an error "RecordError" instead of throwing an empty array (like the REST response)
![image](https://user-images.githubusercontent.com/98479040/191917155-4795d366-7651-4f7d-b8fa-e4b370775643.png)

(cc mathe42 on discord) https://github.com/surrealdb/surrealdb.js/blob/main/src/index.ts#L694

**Comment by auroraisluna** [comment]
bumping :)

**Comment by aratamagna** [comment]
bump, i have this issue as well


error: Uncaught ReferenceError: t is not defined
                                                new Surreal.RecordError(`Record not found: ${t}`)
                                                                                             ^
    at Surreal.#output (https://deno.land/x/surrealdb@v0.2.0/src/mod.ts:451:52)
    at Surreal.<anonymous> (https://deno.land/x/surrealdb@v0.2.0/src/mod.ts:304:38)
    at Surreal.f (https://deno.land/x/surrealdb@v0.2.0/src/classes/emitter.ts:24:9)
    at https://deno.land/x/surrealdb@v0.2.0/src/classes/emitter.ts:31:10
    at Array.forEach (<anonymous>)
    at Surreal.emit (https://deno.land/x/surrealdb@v0.2.0/src/classes/emitter.ts:30:20)
    at Socket.<anonymous> (https://deno.land/x/surrealdb@v0.2.0/src/mod.ts:143:17)
    at https://deno.land/x/surrealdb@v0.2.0/src/classes/emitter.ts:31:10
    at Array.forEach (<anonymous>)
    at Socket.emit (https://deno.land/x/surrealdb@v0.2.0/src/classes/emitter.ts:30:20)

**Comment by mathe42** [comment]
Actualy this is expected behavior. You ask for "give me all data for person with name 'Max'" and there is no "Max". If you want to "ignore" that Error just use `.query` with `SELECT * FROM person:max`

**Comment by auroraisluna** [comment]
> Actualy this is expected behavior. You ask for "give me all data for person with name 'Max'" and there is no "Max". If you want to "ignore" that Error just use `.query` with `SELECT * FROM person:max`
Then it sadly no longer becomes a programmatic query - as in its just a typical SQL/SurrealQL query. I understand this feels right to throw an error but an empty array or 'undefined' or similar would make more sense for this type of function (this is coming from someone who has been using knex.js for years)
Just my two cents.
