### ISSUE TITLE
How to listen live events?

### ISSUE THREAD

**Issue by matigumma** [surrealdb/surrealdb.js#51]
Hi there! 
im trying to fig out how to
listen events on db changes?

**Comment by mathe42** [comment]
In surrealdb live events are currently disabled so they don't work here.

If you want to have a look in how they used to work have a look at ./src/classes/live.ts but we might change them in the future.

**Comment by cope** [comment]
@mathe42 do you maybe have any idea when will live queries be available?

live queries is **the** feature required for me to successfully sell SurrealDB to my team...

**Comment by AndreCox** [comment]
I'm also curious if there is any updates on this?
