### ISSUE TITLE
No typings in NPM package.

### ISSUE THREAD

**Issue by nomyTx** [surrealdb/surrealdb.js#59]
It would be very useful if you could add a bundled .d.ts to the npm package.

**Comment by mathe42** [comment]
https://unpkg.com/browse/surrealdb.js@0.5.0/package.json

Line 4 and the types folder. They are release!

**Comment by nomyTx** [comment]
Sorry for the trouble, I was accidentally downloading `surreal.js` instead of `surrealdb.js`
