### ISSUE TITLE
Change Types on create / change methods to generic

### ISSUE THREAD

**Issue by 0rdep** [surrealdb/surrealdb.js#62]
Hi guys,

On create / change methods, the expected type is Record<string, unknown> & T;

![image](https://user-images.githubusercontent.com/59269331/202872411-e154faa2-51a6-4442-b61b-fd9c9da513d4.png)

But at the end the key type don't matter as we do a JSON.stringify on the object before sending it through web socket
![image](https://user-images.githubusercontent.com/59269331/202872501-fb8a8b4b-9ab1-4a5b-b0a9-1dce5ed87239.png)

Due the typing, it throws errors when passing class instances on create / change methods:

![image](https://user-images.githubusercontent.com/59269331/202872827-4a03400c-5df8-42fb-b5e6-4cfe9e5b9200.png)
![image](https://user-images.githubusercontent.com/59269331/202872860-27137e1e-fe9a-498b-94c0-a4f0b7f06b6f.png)

I think if we just leave the the type to be T it should fix those issues.

**Comment by F9Alejandro** [comment]
So Record<string, unknown> is equivalent to a json object, before it is sent over it is saved in a Record format (takes json and converts to a way it can be parsed over websocket)

I would recommend wrapping the input var as (input as unknown as Record<string, unknown>)

**Comment by kearfy** [comment]
Allthough it works, I don't think this is "correct", as a class is more than "just an object". You could destructure the object and grab the input as the rest parameter? Just watch out with this stuff 😅 

```typescript
create({...input}: Participante) {
    return this.surreal.create('participante', input);
}
```
