### ISSUE TITLE
How to bulk insert from JS client?

### ISSUE THREAD

**Issue by fritzblue** [surrealdb/surrealdb.js#64]
Today the SurrealQL query language [supports multiple-insert](https://surrealdb.com/docs/surrealql/statements/insert) in a single statement as follows:

```sql
INSERT INTO company (name, founded) VALUES ('Acme Inc.', '1967-05-03'), ('Apple Inc.', '1976-04-01');
```

However, the JS client currently only provides `db.create()`, which supports a single record at at a time.

What is the best way to bulk insert when using the JS (Deno / Node / Bun) client? Should one use the raw `db.query()` command? If so, what is the expected syntax?

**Comment by mathe42** [comment]
Yes just user `.query`.

**Comment by fritzblue** [comment]
Thank you @mathe42. What is the correct syntax for providing the `VALUES` list?

**Comment by mathe42** [comment]
Just run
```ts
db.query(`
  INSERT INTO company (name, founded) VALUES ('Acme Inc.', '1967-05-03'), ('Apple Inc.', '1976-04-01');
`)
```

**Comment by sasial-dev** [comment]
The second argument will be the values list
```js
{
  "foo": "bar"
}
```
then in your first argument (query): you'd use `$foo`.
Don't use template variables to prevent SQL injection.

**Comment by mathe42** [comment]
Yes but that is not possible with a not known number auf variables.

If you run on the frontend (e.g. web) SQL injections don't exist with surrealdb (but you have to do proper permissions)

**Comment by evbo** [comment]
@fritzblue +1 but actually bulk loading feature for ALL client APIs is currently missing. Would be great to have a load CSV/JSON/TEXT/BINARY option like all other RDBMS and many graph dbs too (Neo4j, Janus, etc.).

Would you consider broadening the title of this issue to just be "How to bulk insert from client"?

**Comment by mathe42** [comment]
@evbo That would be something that need to best be implemented in [surrelab](https://github.com/surrealdb/surrealdb) not in the client. Same for general bulk inserts. - With that implemented we can add it here...

**Comment by Darkle** [comment]
The following seems to work ok: 

```client.query('INSERT INTO postsTable ($posts);', { posts })```

where `posts` is and array of js objects.

**Comment by kearfy** [comment]
This should indeed be done with the `.query()` method, closing it
