### ISSUE TITLE
Using variables with LIMIT and START cause parse errors

### ISSUE THREAD

**Issue by Darkle** [surrealdb/surrealdb.js#67]
The following will cause a parse error: `db.query('SELECT * FROM logs LIMIT $lmt START $strt', {lmt:10, strt: 2})`

Seems like this hasn't yet landed in the js client: https://github.com/surrealdb/surrealdb/issues/1332

**Comment by kearfy** [comment]
Hey @Darkle, is this still an issue for you? 
I just tested this, and it works just fine!

```typescript
db.query('SELECT id FROM person LIMIT $limit START $start', { start: 0, limit: 1})
```

Note that the order for limit and start is important here (not sure why...)
