### ISSUE TITLE
Can not import SurrealDB from browser

### ISSUE THREAD

**Issue by kevinkleine** [surrealdb/surrealdb.js#70]
Trying to import surrealdb script directly from the browser fails:

```<script src="node_modules/surrealdb.js/esm/index.js" type="module"> </script>```
gives
```Uncaught TypeError: The specifier “isomorphic-ws” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.```

```<script src="node_modules/surrealdb.js/script/index.js"></script>```
gives
```Uncaught ReferenceError: exports is not defined ```

How should I go about this?

**Comment by jareer12** [comment]
Are you importing from plain HTML page?

**Comment by kearfy** [comment]
Heya, I'm hoping that #46 will solve your issue :)

**Comment by kearfy** [comment]
Hi! You should now be able to import the surrealdb.js library into your browser like this:
```html
<script src="path/to/your/script.js" type="module">
```

Then for the actual `script.js`:
```javascript
import Surreal from 'https://unpkg.com/surrealdb.js';
// OR
import Surreal from 'https://cdn.jsdelivr.net/npm/surrealdb.js';
```

Could you confirm if that solves your issue?

**Comment by kearfy** [comment]
Hi, we have shipped the fix for this a while ago, but haven't gotten a confirmation back from you. Will close this as fixed!
