### ISSUE TITLE
PERMISSION doesn't work with selecting a single id

### ISSUE THREAD

**Issue by happysalada** [surrealdb/surrealdb.js#71]
I'm using the permissions feature like
```
DEFINE TABLE media SCHEMALESS  
PERMISSIONS
  FOR select, update, delete WHERE user_email = $auth.email, 
  FOR create NONE;
;
```
I can correctly select all media with this
```
  let media = await db.select("media");
```

however selecting a particular media that exists fails
```
  let medium = await db.select(`${params.id}`);
```
```
RecordError: Record not found: media:01GR6XTHC4ASPSW4VQ00KN2ME1
```
even though that record is included in the all media selected.

For now I can just get all media and filter by id with js as a workaround. Maybe I misunderstood something, but I expected this to work.
Let me know if anything

(I'm running surrealdb from latest master commit and using the latest released version of the js lib).

**Comment by jareer12** [comment]
Duplicated of #43 . [This comment](https://github.com/surrealdb/surrealdb.js/issues/43#issuecomment-1308378048) might help.

**Comment by happysalada** [comment]
It doesnt look like a duplicate, the id exists here, the permission system doesnt allow to return it. Let me know if i misunderstood

**Comment by jareer12** [comment]
> It doesnt look like a duplicate, the id exists here, the permission system doesnt allow to return it. Let me know if i misunderstood

Use `.query()` instead.

**Comment by kearfy** [comment]
I assume that you were using the nightly version of surrealdb there? This should be good in the next release. Thanks!
