### ISSUE TITLE
SurrealDB JS client: invalidate token for specific user

### ISSUE THREAD

**Issue by kelvin2200** [surrealdb/surrealdb.js#76]
It would be nice for the `invalidate()` method on the surreal client, to take an `ID` or some argument so we can invalidate some other user's session in case he's logged in.

**Comment by kearfy** [comment]
You could add this as a feature request on the https://github.com/surrealdb/surrealdb, but as long as something like this is not implemented over there, there is nothing to be implemented in client libraries. Besides that, I think that a feature like that would rather be implemented as a query than a websocket method.

Thanks for the suggestion though!
