### ISSUE TITLE
Code example using variables throws parse error

### ISSUE THREAD

**Issue by W4G1** [surrealdb/surrealdb.js#8]
This snippet is documented here: https://surrealdb.com/docs/surrealql/parameters
```javascript
let people = await db.query("SELECT * FROM article WHERE status IN $status", {
  status: ["live", "draft"],
});
```
It does not seem to work however:
`Error: There was a problem with the database: Parse error on line 1 at character 35 when parsing 'IN $status'`

Environment:
```sh
> deno --version
deno 1.23.2 (release, x86_64-pc-windows-msvc)
v8 10.4.132.8
typescript 4.7.2
> surreal version
surreal 1.0.0-beta.7 for windows on x86_64

**Comment by tobiemh** [comment]
Hi @W4G1, this is an error in the website example, and I'll get this changed on the site. You can use the `INSIDE` operator...

```js
let people = await db.query("SELECT * FROM article WHERE status INSIDE $status", {
  status: ["live", "draft"],
});
```
