### ISSUE TITLE
.query() return strange type

### ISSUE THREAD

**Issue by samson0v** [surrealdb/surrealdb.js#86]
Hi everyone!
I wondered about the type that the `query` function returns (`<Proxy>`).

For example, the `select` function returns the `Array` type as expected so you can simply assign it to a variable as in the following example:
<img width="429" alt="зображення" src="https://user-images.githubusercontent.com/43861229/232811470-8f55870f-8bf6-40a2-afde-2caeb3135f4a.png">

But if I use the `query` function, it returns `Proxy` type, so you have to do the following data manipulation:
<img width="929" alt="зображення" src="https://user-images.githubusercontent.com/43861229/232812118-223dd50e-7cb8-433a-9c8b-8411b55c41f9.png">

Is it a bug or expected behaviour?
Thanks for any reply!

**Versions:**
OS: macOS Ventura 13.1
Firefox: 111.0.1
Vue: 3.2.47
surrealdb.js: 0.6.0

**Comment by kearfy** [comment]
Heya! The return type for `.query()` is indeed a bit weird, and I've been meaning to get into it. Busy week!
I'm not entirely sure however why it returns a proxy for you, that should not be the case...

Question for myself, This is vscode right? If so, which extension do you use to show the argument names for functions? I really like it :)

**Comment by kearfy** [comment]
I actually posted a little snippet in Discord of what I want to change the return type to. Not entirely sure if that is correct as shown there, but it's a start in the right direction. https://discord.com/channels/902568124350599239/1013527402674139268/1097957155040137318

**Comment by samson0v** [comment]
Hi @kearfy, thanks for your reply! I will really appreciate it if you will fix this bug.


> Question for myself, This is vscode right? If so, which extension do you use to show the argument names for functions? I really like it :)

No, it is WebStorm's built-in feature)

**Comment by c43721** [comment]
I've found that the `select` query also returns weird types
![image](https://user-images.githubusercontent.com/55610086/235038836-00bcc274-ca8f-423d-b2f1-82699ded75bf.png)
TS is telling me that the return type is `User[]` when in reality it's actually just `User` (object instead of an array)

**Comment by kearfy** [comment]
Hi @samson0v, I've closed this ticket as I cannot reproduce a `Proxy` being returned...
Could it be that vue does some weird stuff perhaps?

**Comment by samson0v** [comment]
Hi @kearfy, I will be seeing on the result of requests of the network debugger and trying to debug this stuff inside the Vue functions call trace. I let you know about the result.
