### ISSUE TITLE
Type of `db.query()` is confusing

### ISSUE THREAD

**Issue by felix-schindler** [surrealdb/surrealdb.js#91]
`db.query` returns `Promise<Result<T>[]>`. This means that every object in the array has `.result` and or `.error`.

Why isn't the returned type `Promise<Result<T[]>>`? This would make it easier to check for occurred errors since you wouldn't have to check every single object you get back.

Would also make it much easier to pass the array of objects to another function / API response since you would need to loop over the array and push all the `.result` object into a new array first.

**Comment by kearfy** [comment]
So the difficulty with the .query() function is that you can run multiple queries (thus having multiple responses) and every query can return either a single value or an array of values. I know that the typing is wrong ATM, please know that I’m looking into this, also better ways to document this function as the typing really just is complex. There is not a good way around this unfortunately…
